### ISSUE TITLE
No suitable signature - Security Violation

### ISSUE THREAD

**Issue by MahdiPishguy** [SkyrilHD/HP-8570W-Hackintosh#15]
when i want to boot with this repository `EFI` i get this error:

![WhatsApp Image 2021-07-14 at 19 43 27](https://user-images.githubusercontent.com/6617583/125652156-d528e6ce-cb22-41e5-b978-df6a3afaaae9.jpeg)

**Comment by SkyrilHD** [comment]
Wrong issue template.

This happens if you installed macOS without Secure Boot provided by OpenCore. Every 0.6.6 EFI release had SecureBootModel, so if you want to switch to OpenCore you need to copy the necessary files either from or to the Preboot partition. The easiest way would be to disable the "security" all together by changing "Default" to "Disabled" (without quotes).

https://github.com/SkyrilHD/HP-8570W-Hackintosh/blob/deef94824eaa3df1c70ca93d317d879cb9fd6fe1/EFI/OC/config.plist#L1368-L1369
